### ISSUE TITLE
Error Call to undefined function isFeatureAllowed()

### ISSUE THREAD

**Issue by nawalnew** [michnhokn/kirby-cookie-banner#19]
Hello Michael, 
I love your plugin!

Since your Last update the old Helper  isFeatureAllowed() is not working anymore. 

Could you please give a advice how to implement the same functionality?
Somehow Kirby 4.1.2 and the versions before this didnt work either with your new version. 

In my Snippet i had it like this and it worked:
```
  <?php if (isFeatureAllowed('analytics')): ?>
    
Script goes here

  </script>
  <?php endif; ?>
```

Best regards,
Sergej

**Comment by finnge** [comment]
I have the same problem. I identified the root problem to be the hashing of cookies in Kirby. The `CookieBanner::getCookie` returns null because `Cookie::get` returns null.
This is due to the early access in https://github.com/getkirby/kirby/blob/6b7ac66c55ecac20d6b580ef01a667d1806d5c72/src/Http/Cookie.php#L143

**Comment by finnge** [comment]
Hey you could use the `\Michnhokn\CookieBanner::isFeatureAllowed` function as documented in the README.

**Comment by squareclouds** [comment]
@mayfinn somehow it is not working for me after the upgrade to k4, the function always returns false. my cookies look like this:

cookie_status: essential%2Cvisuals%2Cvideos

and i am checking before adding videos likes this:

<?php if (\Michnhokn\CookieBanner::isFeatureAllowed('videos')) : ?>

... stuff

<?php endif ?>

but i always get false. am i doign something wrong?

**Comment by nawalnew** [comment]
> @mayfinn somehow it is not working for me after the upgrade to k4, the function always returns false. my cookies look like this:
> 
> cookie_status: essential%2Cvisuals%2Cvideos
> 
> and i am checking before adding videos likes this:
> 
> ... stuff
> 
> but i always get false. am i doign something wrong?

I want to add the same. Even this \Michnhokn\CookieBanner::isFeatureAllowed returns always false. I#ve tested on clean K4 installation. 

@mayfinn Could you please Provide a working example hof to check the method and get the same results as your K3 Version. Thank you

**Comment by nawalnew** [comment]
The Only Working Solution is at the Moment:

<?php if (isFeatureAllowed('analytics')): ?>

  <?php endif; ?>
  
  In K4 (4.2.0) with your version 1.0.5 and PHP 8.2.4 
  
  
  Ive tested all and needed to revert all my pages back to the old version because your Helper Classes dont work somehow. No Array, No Bool as result. just no error. 
  
  I look forward to help if needed and for a solution to test. 
  Thank you!

**Comment by squareclouds** [comment]
@nawalnew for me version 1.0.9 works fine, there is no need to go so far back to 1.0.5. kirby 4.2 and php 8.2.0
